CREATE TABLE questions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    anime_work_id INT UNSIGNED NOT NULL,
    type ENUM('multiple_choice', 'fill_blank') NOT NULL,
    prompt TEXT NOT NULL,
    choices_json TEXT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    accepted_answers_json TEXT NULL,
    origin ENUM('admin', 'submission') NOT NULL DEFAULT 'admin',
    status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
    submitted_by_token CHAR(64) NULL,
    submitted_nickname VARCHAR(50) NULL,
    filter_flags TEXT NULL,
    reviewed_by INT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    rejection_reason VARCHAR(255) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_questions_work_status_active (anime_work_id, status, is_active),
    KEY idx_questions_submitted_by_token (submitted_by_token),
    KEY idx_questions_status (status),
    CONSTRAINT fk_questions_anime_work FOREIGN KEY (anime_work_id) REFERENCES anime_works (id),
    CONSTRAINT fk_questions_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES admin_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
